Profile settings
krzotki/coin-view pull request #36
Opened 2023-02-02 16:13 UTC by PatrOlen

Forms for updating user's data:
![image](https://user-images.githubusercontent.com/119818428/216379127-f1effa87-0ebf-48a9-93b3-bad53cb8a38d.png)

![image](https://user-images.githubusercontent.com/119818428/216384656-c33f43ba-6bdd-44d7-8c4d-ba353edac808.png)

2023-02-02 16:21 UTC, PatrOlen commented
For all intents and purposes, the password change logic is temporary, before the way passwords are hashed and validated is reworked.

2023-02-02 18:03 UTC, krzotki requested changes

2023-02-02 18:03 UTC, krzotki commented on src/client/components/Forms/ChangePasswordForm.tsx
> +          )} */}
remove unused

2023-02-02 18:03 UTC, krzotki commented on src/client/components/Forms/ModifyProfileForm.tsx
> +    const productupdate = session?.user?.productupdate;
As discussed

2023-02-02 18:03 UTC, krzotki commented on src/client/components/Forms/ModifyProfileForm.tsx
> +      console.log(email_sub);
remove log

2023-02-02 18:03 UTC, krzotki commented on src/client/components/Forms/ModifyProfileForm.tsx
> +          src={`/chevron_${chevronIconMode}.svg`}
Please rename it

2023-02-02 18:03 UTC, krzotki commented on src/client/components/Forms/ModifyProfileForm.tsx
> +          )} */}
Remove unused

2023-02-11 19:18 UTC, krzotki approved these changes
Good job 🥇

2023-02-11 19:18 UTC, merged